//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DOCUMENT
    {
        public int DOC_ID { get; set; }
        public string DOC_NAME { get; set; }
        public string DOC_FILE { get; set; }
        public string DOC_PATH { get; set; }
        public int DOC_ATYPE { get; set; }
        public int DOC_AID { get; set; }
        public int DOC_NID { get; set; }
        public string DOC_SIZE { get; set; }
        public string DOC_TYPE { get; set; }
        public Nullable<int> DOC_ORDER { get; set; }
        public Nullable<System.DateTime> DOC_DATET { get; set; }
        public string DOC_V01 { get; set; }
        public string DOC_V02 { get; set; }
        public string DOC_V03 { get; set; }
        public string DOC_V04 { get; set; }
        public string DOC_V05 { get; set; }
        public string DOC_V06 { get; set; }
        public string DOC_V07 { get; set; }
        public string DOC_V08 { get; set; }
        public Nullable<int> DOC_I01 { get; set; }
        public Nullable<int> DOC_I02 { get; set; }
        public Nullable<int> DOC_I03 { get; set; }
        public Nullable<int> DOC_I04 { get; set; }
        public Nullable<int> DOC_I05 { get; set; }
        public Nullable<System.DateTime> DOC_D01 { get; set; }
        public Nullable<System.DateTime> DOC_D02 { get; set; }
        public Nullable<System.DateTime> DOC_D03 { get; set; }
        public int DOC_STATUS { get; set; }
    }
}
