//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Log
    {
        public int Log_ID { get; set; }
        public string Log_Type { get; set; }
        public string Log_UName { get; set; }
        public int Log_UID { get; set; }
        public string Log_Content { get; set; }
        public System.DateTime Log_Date { get; set; }
        public Nullable<int> Log_Level { get; set; }
        public string Log_Remark { get; set; }
        public string Log_V01 { get; set; }
        public string Log_V02 { get; set; }
        public string Log_V03 { get; set; }
        public string Log_V04 { get; set; }
        public string Log_V05 { get; set; }
        public string Log_V06 { get; set; }
        public string Log_V07 { get; set; }
        public Nullable<int> Log_I01 { get; set; }
        public Nullable<int> Log_I02 { get; set; }
        public Nullable<int> Log_I03 { get; set; }
        public Nullable<System.DateTime> Log_D01 { get; set; }
        public Nullable<System.DateTime> Log_D02 { get; set; }
    }
}
