//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Message
    {
        public int Message_ID { get; set; }
        public string Message_NO { get; set; }
        public string Message_WH { get; set; }
        public string Message_Title { get; set; }
        public Nullable<System.DateTime> Message_Date { get; set; }
        public string Message_Type { get; set; }
        public string Message_SendUnit { get; set; }
        public string Message_ReceiveUnit { get; set; }
        public string Message_Sender { get; set; }
        public string Message_Remark { get; set; }
        public string MG_V01 { get; set; }
        public string MG_V02 { get; set; }
        public string MG_V03 { get; set; }
        public Nullable<int> MG_V04 { get; set; }
        public Nullable<System.DateTime> MG_V05 { get; set; }
        public int MG_mid { get; set; }
        public string Message_BGQX { get; set; }
    }
}
