//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MODEL
    {
        public int MD_ID { get; set; }
        public int MD_PID { get; set; }
        public Nullable<int> MD_ORDER { get; set; }
        public string MD_NAME { get; set; }
        public int MD_ISARCHIVE { get; set; }
        public string MD_PATH { get; set; }
        public string MD_ICON { get; set; }
        public int MD_STATUS { get; set; }
        public string MD_CONTROLLERS { get; set; }
        public string MD_ACTION { get; set; }
        public string MD_V01 { get; set; }
        public string MD_V02 { get; set; }
        public string MD_V03 { get; set; }
        public string MD_V04 { get; set; }
        public Nullable<int> MD_I01 { get; set; }
        public Nullable<int> MD_I02 { get; set; }
        public Nullable<int> MD_I03 { get; set; }
    }
}
