//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProjectInfo
    {
        public int PR_ID { get; set; }
        public string PR_Name { get; set; }
        public string PR_BuildUnit { get; set; }
        public string PR_BuildUnitPhone { get; set; }
        public string PR_BuildUnitAddress { get; set; }
        public string PR_BuildAdress { get; set; }
        public string PR_DesignUnit { get; set; }
        public string PR_ConstructionUnit { get; set; }
        public string PR_SupervisionName { get; set; }
        public string PR_TotalArea { get; set; }
        public Nullable<System.DateTime> PR_StartDay { get; set; }
        public Nullable<System.DateTime> PR_EndDay { get; set; }
        public Nullable<System.DateTime> PR_StorageDay { get; set; }
        public string PR_BGQX { get; set; }
        public string PR_TotalInvest { get; set; }
        public string PR_ARReceiver { get; set; }
        public string PR_RKReceiver { get; set; }
        public Nullable<int> PR_TotalNum { get; set; }
        public Nullable<int> PR_FileNum { get; set; }
        public Nullable<int> PR_ImageNum { get; set; }
        public Nullable<int> PR_PhotoNum { get; set; }
        public Nullable<int> PR_VideoNum { get; set; }
        public Nullable<int> PR_VoiceNum { get; set; }
        public string PR_BZUnit { get; set; }
        public Nullable<System.DateTime> PR_BZDay { get; set; }
        public string PR_ProAccounts { get; set; }
        public string PR_ProAccountsUnit { get; set; }
        public Nullable<int> PR_MID { get; set; }
        public string PR_BH { get; set; }
    }
}
