//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Query
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public string Fields { get; set; }
        public Nullable<int> Grade { get; set; }
        public string Table { get; set; }
    }
}
