//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QX
    {
        public int QX_ID { get; set; }
        public int QX_RID { get; set; }
        public int QX_MID { get; set; }
        public int QX_STATUS { get; set; }
        public string QX_V01 { get; set; }
        public string QX_V02 { get; set; }
        public string QX_V03 { get; set; }
        public Nullable<int> QX_I01 { get; set; }
        public Nullable<int> QX_I02 { get; set; }
        public Nullable<int> QX_I03 { get; set; }
        public Nullable<System.DateTime> QX_D01 { get; set; }
        public Nullable<System.DateTime> QX_D02 { get; set; }
    }
}
