//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ROLE
    {
        public int ROLE_ID { get; set; }
        public string ROLE_NAME { get; set; }
        public string ROLE_REMARK { get; set; }
        public int ROLE_STATUS { get; set; }
        public int ROLE_VIEWPIC { get; set; }
        public int ROLE_MODIFY { get; set; }
        public string ROLE_V01 { get; set; }
        public string ROLE_V02 { get; set; }
        public string ROLE_V03 { get; set; }
        public string ROLE_V04 { get; set; }
        public string ROLE_V05 { get; set; }
        public Nullable<int> ROLE_I01 { get; set; }
        public Nullable<int> ROLE_I02 { get; set; }
        public Nullable<int> ROLE_I03 { get; set; }
        public Nullable<int> ROLE_I04 { get; set; }
        public Nullable<int> ROLE_I05 { get; set; }
        public Nullable<System.DateTime> ROLE_D01 { get; set; }
        public Nullable<System.DateTime> ROLE_D02 { get; set; }
        public Nullable<System.DateTime> ROLE_DATE { get; set; }
        public Nullable<int> ROLE_RID { get; set; }
    }
}
