//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SINGLEINFO
    {
        public int SG_ID { get; set; }
        public string SG_Name { get; set; }
        public string SG_Xnum { get; set; }
        public string SG_Type { get; set; }
        public string SG_Area { get; set; }
        public string SG_Form { get; set; }
        public string SG_Bnum { get; set; }
        public string SG_High { get; set; }
        public string SG_Znum { get; set; }
        public string SG_Deep { get; set; }
        public string SG_Underfloor { get; set; }
        public string SG_Overfloor { get; set; }
        public string SG_CZ { get; set; }
        public string SG_Length { get; set; }
        public string SG_Vnum { get; set; }
        public string SG_PD { get; set; }
        public string SG_Norms { get; set; }
        public string SG_Dunit { get; set; }
        public string SG_Wunit { get; set; }
        public string SG_Junit { get; set; }
        public string SG_Remark { get; set; }
        public Nullable<int> SG_V01 { get; set; }
        public Nullable<int> SG_V02 { get; set; }
        public Nullable<System.DateTime> SG_V03 { get; set; }
        public string SG_V04 { get; set; }
        public string SG_V05 { get; set; }
        public string SG_V06 { get; set; }
        public string SG_V07 { get; set; }
        public string SG_V08 { get; set; }
        public string SG_V09 { get; set; }
        public string SG_V10 { get; set; }
        public string SG_PID { get; set; }
    }
}
