//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYSWD
    {
        public int WD_ID { get; set; }
        public string WD_NAME { get; set; }
        public Nullable<int> WD_CODE { get; set; }
        public string WD_TYPE { get; set; }
        public Nullable<int> WD_ORDER { get; set; }
        public Nullable<int> WD_STATUS { get; set; }
    }
}
