//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TEXT
    {
        public int TEXT_ID { get; set; }
        public int TEXT_DOCID { get; set; }
        public string TEXT_CONTENT { get; set; }
        public int TEXT_PAGENUM { get; set; }
        public int TEXT_STATUS { get; set; }
        public string TEXT_V01 { get; set; }
        public string TEXT_V02 { get; set; }
        public string TEXT_V03 { get; set; }
        public Nullable<System.DateTime> TEXT_D01 { get; set; }
        public Nullable<System.DateTime> TEXT_D02 { get; set; }
        public Nullable<int> TEXT_I01 { get; set; }
        public Nullable<int> TEXT_I02 { get; set; }
    }
}
