//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WSAJ1
    {
        public int WS1_ID { get; set; }
        public string WS1_JH { get; set; }
        public string WS1_TM { get; set; }
        public string WS1_BGQX { get; set; }
        public string WS1_YEAR { get; set; }
        public Nullable<int> WS1_FileNum { get; set; }
        public Nullable<int> WS1_DrawNum { get; set; }
        public Nullable<int> WS1_OtherNum { get; set; }
        public Nullable<System.DateTime> WS1_GDRQ { get; set; }
        public string WS1_BZ { get; set; }
        public Nullable<int> WS1_HH { get; set; }
        public string WS1_HJBH { get; set; }
        public string WS1_PID { get; set; }
        public Nullable<int> WS1_MID { get; set; }
        public string WS1_V01 { get; set; }
    }
}
