//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WSJN1
    {
        public int JN1_ID { get; set; }
        public string JN1_Name { get; set; }
        public Nullable<int> JN1_XH { get; set; }
        public string JN1_BH { get; set; }
        public Nullable<int> JN1_YS { get; set; }
        public Nullable<int> JN1_Start { get; set; }
        public Nullable<int> JN1_End { get; set; }
        public string JN1_Type { get; set; }
        public string JN1_ZRZ { get; set; }
        public Nullable<System.DateTime> JN1_RQ { get; set; }
        public string JN1_Remark { get; set; }
        public string JN1_Scan { get; set; }
        public string JN1_AJID { get; set; }
    }
}
