//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TEXT1
    {
        public int TEXT_ID { get; set; }
        public int TEXT_DOCID { get; set; }
        public string TEXT_CONTENT { get; set; }
        public int TEXT_PAGENUM { get; set; }
        public int TEXT_STATUS { get; set; }
        public string TEXT_V01 { get; set; }
        public string TEXT_V02 { get; set; }
        public string TEXT_V03 { get; set; }
        public Nullable<System.DateTime> TEXT_D01 { get; set; }
        public Nullable<System.DateTime> TEXT_D02 { get; set; }
        public Nullable<int> TEXT_I01 { get; set; }
        public Nullable<int> TEXT_I02 { get; set; }
        public Nullable<int> DOC_ID { get; set; }
        public string DOC_NAME { get; set; }
        public string DOC_FILE { get; set; }
        public string DOC_PATH { get; set; }
        public Nullable<int> DOC_ATYPE { get; set; }
        public Nullable<int> DOC_AID { get; set; }
        public Nullable<int> DOC_NID { get; set; }
        public string DOC_SIZE { get; set; }
        public string DOC_TYPE { get; set; }
        public Nullable<int> DOC_ORDER { get; set; }
        public Nullable<System.DateTime> DOC_DATET { get; set; }
        public string DOC_V01 { get; set; }
        public string DOC_V02 { get; set; }
        public string DOC_V03 { get; set; }
        public string DOC_V04 { get; set; }
        public string DOC_V05 { get; set; }
        public string DOC_V06 { get; set; }
        public string DOC_V07 { get; set; }
        public string DOC_V08 { get; set; }
        public Nullable<int> DOC_I01 { get; set; }
        public Nullable<int> DOC_I02 { get; set; }
        public Nullable<int> DOC_I03 { get; set; }
        public Nullable<int> DOC_I04 { get; set; }
        public Nullable<int> DOC_I05 { get; set; }
        public Nullable<System.DateTime> DOC_D01 { get; set; }
        public Nullable<System.DateTime> DOC_D02 { get; set; }
        public Nullable<System.DateTime> DOC_D03 { get; set; }
        public Nullable<int> DOC_STATUS { get; set; }
        public Nullable<int> JN1_ID { get; set; }
        public string JN1_Name { get; set; }
        public Nullable<int> JN1_XH { get; set; }
        public string JN1_BH { get; set; }
        public Nullable<int> JN1_YS { get; set; }
        public Nullable<int> JN1_Start { get; set; }
        public Nullable<int> JN1_End { get; set; }
        public string JN1_Type { get; set; }
        public string JN1_ZRZ { get; set; }
        public Nullable<System.DateTime> JN1_RQ { get; set; }
        public string JN1_Remark { get; set; }
        public string JN1_Scan { get; set; }
        public string JN1_AJID { get; set; }
        public Nullable<int> WS1_ID { get; set; }
        public string WS1_JH { get; set; }
        public string WS1_TM { get; set; }
        public string WS1_BGQX { get; set; }
        public string WS1_YEAR { get; set; }
        public Nullable<int> WS1_FileNum { get; set; }
        public Nullable<int> WS1_DrawNum { get; set; }
        public Nullable<int> WS1_OtherNum { get; set; }
        public Nullable<System.DateTime> WS1_GDRQ { get; set; }
        public string WS1_BZ { get; set; }
        public Nullable<int> WS1_HH { get; set; }
        public string WS1_HJBH { get; set; }
        public string WS1_PID { get; set; }
        public Nullable<int> WS1_MID { get; set; }
        public string WS1_V01 { get; set; }
        public Nullable<int> MD_ID { get; set; }
        public Nullable<int> MD_PID { get; set; }
        public Nullable<int> MD_ORDER { get; set; }
        public string MD_NAME { get; set; }
        public Nullable<int> MD_ISARCHIVE { get; set; }
        public string MD_PATH { get; set; }
        public string MD_ICON { get; set; }
        public Nullable<int> MD_STATUS { get; set; }
        public string MD_CONTROLLERS { get; set; }
        public string MD_ACTION { get; set; }
        public string MD_V01 { get; set; }
        public string MD_V02 { get; set; }
        public string MD_V03 { get; set; }
        public string MD_V04 { get; set; }
        public Nullable<int> MD_I01 { get; set; }
        public Nullable<int> MD_I02 { get; set; }
        public Nullable<int> MD_I03 { get; set; }
    }
}
