//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_USER
    {
        public int U_ID { get; set; }
        public string U_NAME { get; set; }
        public string U_PWD { get; set; }
        public int U_ROLEID { get; set; }
        public Nullable<int> U_DEPARMENT { get; set; }
        public string U_ZW { get; set; }
        public int U_STATUS { get; set; }
        public string U_REALNAME { get; set; }
        public string U_PHONE { get; set; }
        public string U_EMAIL { get; set; }
        public string U_REMARK { get; set; }
        public string U_SEX { get; set; }
        public string U_PHOTO { get; set; }
        public string U_V01 { get; set; }
        public string U_V02 { get; set; }
        public string U_V03 { get; set; }
        public string U_V04 { get; set; }
        public string U_V05 { get; set; }
        public Nullable<int> U_I01 { get; set; }
        public Nullable<int> U_I02 { get; set; }
        public Nullable<int> U_I03 { get; set; }
        public Nullable<int> U_I04 { get; set; }
        public Nullable<int> U_I05 { get; set; }
        public Nullable<System.DateTime> U_D01 { get; set; }
        public Nullable<System.DateTime> U_D02 { get; set; }
        public Nullable<System.DateTime> U_DATE { get; set; }
        public string U_IP { get; set; }
        public Nullable<int> U_ISIP { get; set; }
        public Nullable<int> ROLE_ID { get; set; }
        public string ROLE_NAME { get; set; }
        public string ROLE_REMARK { get; set; }
        public Nullable<int> ROLE_STATUS { get; set; }
        public Nullable<int> ROLE_VIEWPIC { get; set; }
        public Nullable<int> ROLE_MODIFY { get; set; }
        public string ROLE_V01 { get; set; }
        public string ROLE_V02 { get; set; }
        public string ROLE_V03 { get; set; }
        public string ROLE_V04 { get; set; }
        public string ROLE_V05 { get; set; }
        public Nullable<int> ROLE_I01 { get; set; }
        public Nullable<int> ROLE_I02 { get; set; }
        public Nullable<int> ROLE_I03 { get; set; }
        public Nullable<int> ROLE_I04 { get; set; }
        public Nullable<int> ROLE_I05 { get; set; }
        public Nullable<System.DateTime> ROLE_D01 { get; set; }
        public Nullable<System.DateTime> ROLE_D02 { get; set; }
        public Nullable<System.DateTime> ROLE_DATE { get; set; }
        public Nullable<int> ROLE_RID { get; set; }
    }
}
