//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WSAJ
    {
        public int WS1_ID { get; set; }
        public string WS1_JH { get; set; }
        public string WS1_TM { get; set; }
        public string WS1_BGQX { get; set; }
        public string WS1_YEAR { get; set; }
        public Nullable<int> WS1_FileNum { get; set; }
        public Nullable<int> WS1_DrawNum { get; set; }
        public Nullable<int> WS1_OtherNum { get; set; }
        public Nullable<System.DateTime> WS1_GDRQ { get; set; }
        public string WS1_BZ { get; set; }
        public Nullable<int> WS1_HH { get; set; }
        public string WS1_HJBH { get; set; }
        public string WS1_PID { get; set; }
        public Nullable<int> WS1_MID { get; set; }
        public string WS1_V01 { get; set; }
        public Nullable<int> MD_ID { get; set; }
        public Nullable<int> MD_PID { get; set; }
        public Nullable<int> MD_ORDER { get; set; }
        public string MD_NAME { get; set; }
        public Nullable<int> MD_ISARCHIVE { get; set; }
        public string MD_PATH { get; set; }
        public string MD_ICON { get; set; }
        public Nullable<int> MD_STATUS { get; set; }
        public string MD_CONTROLLERS { get; set; }
        public string MD_ACTION { get; set; }
        public string MD_V01 { get; set; }
        public string MD_V02 { get; set; }
        public string MD_V03 { get; set; }
        public string MD_V04 { get; set; }
        public Nullable<int> MD_I01 { get; set; }
        public Nullable<int> MD_I02 { get; set; }
        public Nullable<int> MD_I03 { get; set; }
        public Nullable<int> PR_ID { get; set; }
        public string PR_Name { get; set; }
        public string PR_BuildUnit { get; set; }
        public string PR_BuildUnitPhone { get; set; }
        public string PR_BuildUnitAddress { get; set; }
        public string PR_BuildAdress { get; set; }
        public string PR_DesignUnit { get; set; }
        public string PR_ConstructionUnit { get; set; }
        public string PR_SupervisionName { get; set; }
        public string PR_TotalArea { get; set; }
        public Nullable<System.DateTime> PR_StartDay { get; set; }
        public Nullable<System.DateTime> PR_EndDay { get; set; }
        public Nullable<System.DateTime> PR_StorageDay { get; set; }
        public string PR_BGQX { get; set; }
        public string PR_TotalInvest { get; set; }
        public string PR_ARReceiver { get; set; }
        public string PR_RKReceiver { get; set; }
        public Nullable<int> PR_TotalNum { get; set; }
        public Nullable<int> PR_FileNum { get; set; }
        public Nullable<int> PR_ImageNum { get; set; }
        public Nullable<int> PR_PhotoNum { get; set; }
        public Nullable<int> PR_VideoNum { get; set; }
        public Nullable<int> PR_VoiceNum { get; set; }
        public string PR_BZUnit { get; set; }
        public Nullable<System.DateTime> PR_BZDay { get; set; }
        public string PR_ProAccounts { get; set; }
        public string PR_ProAccountsUnit { get; set; }
        public Nullable<int> PR_MID { get; set; }
        public string PR_BH { get; set; }
    }
}
